#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

export DATASET="${DATASET:-transxion_full}"
export TOKENIZED_BACKEND="${TOKENIZED_BACKEND:-lmdb}"
export FORCE_REBUILD_TOKENIZER=0
export FORCE_REENCODE=0
export DO_TRAIN=1
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-128}"
export DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"
export DATALOADER_PREFETCH_FACTOR="${DATALOADER_PREFETCH_FACTOR:-4}"
export DATALOADER_PERSISTENT_WORKERS="${DATALOADER_PERSISTENT_WORKERS:-1}"
export DATALOADER_PIN_MEMORY="${DATALOADER_PIN_MEMORY:-1}"
export ENABLE_TF32="${ENABLE_TF32:-1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

bash run.sh
