from __future__ import annotations

import argparse
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from src.common.fs import ensure_dir


def _utc_iso(ts: datetime) -> str:
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    return ts.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def _generate_transxion(output_dir: Path, num_entities: int, num_transactions: int, seed: int) -> None:
    rng = np.random.default_rng(seed)
    ensure_dir(output_dir)

    regions = np.array(["UK", "EU", "US", "SG", "AE"])
    currencies = np.array(["GBP", "EUR", "USD", "SGD", "AED"])
    payment_formats = np.array(["card", "bank_transfer", "cash", "crypto"])
    banks = np.array(["bank_a", "bank_b", "bank_c", "bank_d"])
    age_buckets = np.array(["18_24", "25_34", "35_44", "45_54", "55_64", "65_plus"])

    person_ids = np.arange(num_entities, dtype=np.int64)
    account_ids = np.arange(num_entities, dtype=np.int64)

    persons = pd.DataFrame(
        {
            "person_id": person_ids,
            "entity_type": "person",
            "age_bucket": rng.choice(age_buckets, size=num_entities),
            "region": rng.choice(regions, size=num_entities),
        }
    )

    accounts = pd.DataFrame(
        {
            "account_id": account_ids,
            "person_id": person_ids,
            "created_at": pd.Timestamp("2024-01-01", tz="UTC")
            + pd.to_timedelta(rng.integers(0, 180, size=num_entities), unit="D"),
            "account_region": rng.choice(regions, size=num_entities),
        }
    )
    accounts["created_at"] = accounts["created_at"].dt.strftime("%Y-%m-%dT%H:%M:%SZ")

    num_merchants = max(200, num_entities // 5)
    merchant_ids = np.arange(num_merchants, dtype=np.int64)
    merchants = pd.DataFrame(
        {
            "merchant_id": merchant_ids,
            "entity_type": "merchant",
            "merchant_region": rng.choice(regions, size=num_merchants),
            "merchant_category": rng.choice(
                ["grocery", "electronics", "travel", "entertainment", "services"], size=num_merchants
            ),
        }
    )

    base_time = datetime(2024, 1, 1, tzinfo=timezone.utc)
    sender_id = rng.choice(account_ids, size=num_transactions)
    receiver_is_merchant = rng.random(size=num_transactions) < 0.75
    receiver_merchant = rng.choice(merchant_ids, size=num_transactions)
    receiver_account = rng.choice(account_ids, size=num_transactions)
    receiver_id = np.where(receiver_is_merchant, receiver_merchant + 10_000_000, receiver_account)

    amount = rng.lognormal(mean=3.5, sigma=1.0, size=num_transactions).round(2)
    currency = rng.choice(currencies, size=num_transactions)
    payment_format = rng.choice(payment_formats, size=num_transactions, p=[0.55, 0.35, 0.08, 0.02])
    sender_bank = rng.choice(banks, size=num_transactions)
    receiver_bank = rng.choice(banks, size=num_transactions)

    is_laundering = (rng.random(size=num_transactions) < 0.01).astype(np.int64)
    high_amount = amount > np.quantile(amount, 0.995)
    is_laundering = np.maximum(is_laundering, high_amount.astype(np.int64))

    timestamps = np.array(
        [
            _utc_iso(base_time + timedelta(minutes=int(m)))
            for m in rng.integers(0, 60 * 24 * 365, size=num_transactions)
        ]
    )

    transactions = pd.DataFrame(
        {
            "transaction_id": np.arange(num_transactions, dtype=np.int64),
            "timestamp": timestamps,
            "sender_id": sender_id,
            "receiver_id": receiver_id,
            "amount": amount,
            "currency": currency,
            "payment_format": payment_format,
            "sender_bank": sender_bank,
            "receiver_bank": receiver_bank,
            "is_laundering": is_laundering,
        }
    )

    persons.to_csv(output_dir / "persons.csv", index=False)
    accounts.to_csv(output_dir / "accounts.csv", index=False)
    merchants.to_csv(output_dir / "merchants.csv", index=False)
    transactions.to_csv(output_dir / "transactions.csv", index=False)

    metadata = {
        "dataset": "transxion_synthetic",
        "generated_at": _utc_iso(datetime.now(tz=timezone.utc)),
        "num_entities": int(num_entities),
        "num_merchants": int(num_merchants),
        "num_transactions": int(num_transactions),
        "note": "Synthetic dataset generated by PRAGMA-lite downloader for local reproducible experiments.",
        "receiver_id_convention": "merchant ids are offset by +10_000_000 to avoid collision with account ids",
    }
    (output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")


def _generate_tabformer(output_dir: Path, num_cards: int, num_rows: int, seed: int) -> None:
    rng = np.random.default_rng(seed)
    ensure_dir(output_dir)

    card_id = rng.integers(0, num_cards, size=num_rows)
    mcc = rng.choice(["grocery", "travel", "gas", "restaurant", "online", "services"], size=num_rows)
    amount = rng.lognormal(mean=3.0, sigma=0.9, size=num_rows).round(2)
    country = rng.choice(["UK", "US", "DE", "FR", "SG"], size=num_rows)
    hour = rng.integers(0, 24, size=num_rows)
    day = rng.integers(0, 365, size=num_rows)
    timestamp = pd.Timestamp("2024-01-01", tz="UTC") + pd.to_timedelta(day, unit="D") + pd.to_timedelta(hour, unit="h")

    df = pd.DataFrame(
        {
            "card_id": card_id,
            "timestamp": timestamp.dt.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "mcc": mcc,
            "amount": amount,
            "country": country,
        }
    )
    df.to_csv(output_dir / "card_transaction.v1.csv", index=False)
    metadata = {
        "dataset": "tabformer_synthetic",
        "generated_at": _utc_iso(datetime.now(tz=timezone.utc)),
        "num_cards": int(num_cards),
        "num_rows": int(num_rows),
    }
    (output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True, choices=["transxion", "tabformer"])
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num_entities", type=int, default=5000)
    parser.add_argument("--num_transactions", type=int, default=200000)
    parser.add_argument("--num_cards", type=int, default=2000)
    parser.add_argument("--num_rows", type=int, default=200000)
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    if args.dataset == "transxion":
        _generate_transxion(out_dir, args.num_entities, args.num_transactions, args.seed)
    else:
        _generate_tabformer(out_dir, args.num_cards, args.num_rows, args.seed)


if __name__ == "__main__":
    main()
